# Generated by Django 3.2.9 on 2021-11-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Employee'), (3, 'Technician')], default=3, null=True),
        ),
    ]
